version: '3'

services:
    lti1p3_nginx:
        container_name: lti1p3_nginx
        image: nginx:stable
        networks:
            - lti1p3
        ports:
            - "8008:80"
        volumes:
            - .:/var/www/html:cached
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
        working_dir: /etc/nginx/conf.d

    lti1p3_phpfpm:
        container_name: lti1p3_phpfpm
        build:
            context: ./docker/phpfpm
        expose:
            - 9000
        networks:
            - lti1p3
        volumes:
            - .:/var/www/html:cached
        working_dir: /var/www/html

    lti1p3_redis:
        container_name: lti1p3_redis
        image: redis
        command: ["redis-server", "--appendonly", "yes"]
        hostname: lti1p3_redis
        networks:
            - lti1p3
        ports:
            - "6381:6379"
        volumes:
            - lti1p3_redis_volume:/data

volumes:
    lti1p3_redis_volume:
        driver: local

networks:
    lti1p3:
        external: true
