parameters:
    platforms:
        moodleDemoCloud:
            name: "Moodle demo cloud"
            audience: "https://taodemo.moodlecloud.com"
            oAuth2AccessTokenUrl: "https://taodemo.moodlecloud.com/mod/lti/token.php"
            oidcAuthUrl: "https://taodemo.moodlecloud.com/mod/lti/auth.php"
        imsCertPlatform:
            name: "IMS Demo Platform #768"
            audience: "https://lti-ri.imsglobal.org"
            oAuth2AccessTokenUrl: "https://lti-ri.imsglobal.org/platforms/768/access_tokens"
            oidcAuthUrl: "https://lti-ri.imsglobal.org/platforms/768/authorizations/new"
        myLocalPlatform:
            name: "My local platform"
            audience: "myLocalPlatform"
            oAuth2AccessTokenUrl: "http://localhost:8000/platform/oauth2/access-token"
            oidcAuthUrl: "http://localhost:8000/platform/oidc/authorization"
        ltiLauncher:
            name: "LTI Launcher"
            audience: "lti_launcher"
            oAuth2AccessTokenUrl: "http://localhost:9393/oauth2/token"
            oidcAuthUrl: "http://localhost:9393/auth"
    tools:
        imsCertTool:
            name: "IMS Demo Tool #800"
            deepLaunchUrl: "https://lti-ri.imsglobal.org/lti/tools/800/deep_link_launches"
            oidcLoginInitiationUrl: "https://lti-ri.imsglobal.org/lti/tools/800/login_initiations"
        myLocalTool:
            name: "My Local Tool"
            deepLaunchUrl: "http://localhost:8000/tool/deep-link/launch"
            oidcLoginInitiationUrl: "http://localhost:8000/tool/oidc/login-initiation"
        myLocalToolForMoodle:
            name: "My Local Tool for moodle"
            deepLaunchUrl: "http://localhost:8000/tool/deep-link/launch"
            oidcLoginInitiationUrl: "http://localhost:8000/tool/oidc/login-initiation"
    keyChains:
        myKeySet1:
            kid1:
                publicKey: "file://%kernel.project_dir%/config/keys/tool/public.key"
                privateKey: "file://%kernel.project_dir%/config/keys/tool/private.key"
                privateKeyPassPhrase: ~
        myKeySet2:
            kid2:
                publicKey: "file://%kernel.project_dir%/config/keys/platform/public.key"
                privateKey: "file://%kernel.project_dir%/config/keys/platform/private.key"
                privateKeyPassPhrase: ~
    deployments:
        1:
            oAuth2ClientId: "hYhw82beq2NjEyH"
            platform:
                id: "moodleDemoCloud"
                keyChain: ~
                jwksUrl: "https://taodemo.moodlecloud.com/mod/lti/certs.php"
            tool:
                id: "myLocalToolForMoodle"
                keyChain: "kid1"
                jwksUrl: "http://localhost:8000/lti/myKeySet1/.well-know/jwks.json"
        imsPlatformDeploy:
            oAuth2ClientId: "12345"
            platform:
                id: "imsCertPlatform"
                keyChain: ~
                jwksUrl: "https://lti-ri.imsglobal.org/platforms/768/platform_keys/790.json"
            tool:
                id: "myLocalTool"
                keyChain: "kid1"
                jwksUrl: "http://localhost:8000/lti/myKeySet1/.well-know/jwks.json"
        imsToolDeploy:
            oAuth2ClientId: "12345"
            platform:
                id: "myLocalPlatform"
                keyChain: "kid1"
                jwksUrl: "http://35bedd79.ngrok.io/lti/myKeySet1/.well-know/jwks.json"
            tool:
                id: "imsCertTool"
                keyChain: "kid1"
                jwksUrl: "http://localhost:8000/lti/myKeySet1/.well-know/jwks.json"
        localToolDeploy:
            oAuth2ClientId: "12345"
            platform:
                id: "myLocalPlatform"
                keyChain: "kid2"
                jwksUrl: "http://localhost:8000/lti/myKeySet2/.well-know/jwks.json"
            tool:
                id: "myLocalTool"
                keyChain: "kid1"
                jwksUrl: "http://localhost:8000/lti/myKeySet1/.well-know/jwks.json"
        da813c03-be59-4755-bfc1-023356d14960:
            oAuth2ClientId: "12345"
            platform:
                id: "ltiLauncher"
                keyChain: ~
                jwksUrl: "http://localhost:9393/keypairs"
            tool:
                id: "myLocalTool"
                keyChain: "kid1"
                jwksUrl: "http://localhost:8000/lti/myKeySet1/.well-know/jwks.json"



