lti_jwks:
    methods: [GET]
    path: /lti/.well-know/{identifier}/jwks.json
    controller: App\Action\Jwks\JwksAction

tool_security_oidc_login_initiation:
    methods: [GET, POST]
    path: /tool/oidc/login-initiation
    controller: App\Action\Tool\Security\Oidc\LoginInitiationAction

tool_security_deep_link_launch:
    methods: [GET, POST]
    path: /tool/deep-link/launch
    controller: App\Action\Tool\Security\DeepLink\LaunchAction

tool_feature:
    methods: [GET, POST]
    path: /tool/feature
    controller: App\Action\Tool\Feature\FeatureAction