# Jwks
lti_jwks:
    methods: [GET]
    path: /lti/{group}/.well-know/jwks.json
    controller: App\Action\Jwks\JwksAction

# Tools
tool_security_oidc_login_initiation:
    methods: [GET, POST]
    path: /tool/oidc/login-initiation
    controller: App\Action\Tool\Security\Oidc\LoginInitiationAction

tool_security_deep_link_launch:
    methods: [GET, POST]
    path: /tool/deep-link/launch
    controller: App\Action\Tool\Security\DeepLink\LaunchAction

# Platforms
platform_security_oidc_login_initiation:
    methods: [GET, POST]
    path: /platform/oidc/login-request
    controller: App\Action\Platform\Security\Oidc\LoginRequestAction

platform_security_oidc_authorization:
    methods: [GET, POST]
    path: /platform/oidc/authorization
    controller: App\Action\Platform\Security\Oidc\AuthorizationAction

platform_security_oauth2_access_token:
    methods: [GET, POST]
    path: /platform/oauth2/access-token
    controller: App\Action\Platform\Security\OAuth2\AccessTokenAction