imports:
    - { resource: 'lti.yaml' }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Action\:
        resource: '../src/Action'
        tags: ['controller.service_arguments']

    App\Lti\Core\Security\Key\KeyChainRepositoryInterface:
        factory:   ['@App\Lti\Builder\KeyChainRepositoryBuilder', 'build']
        arguments: ['%kernel.project_dir%/config/lti.yaml']

    App\Lti\Core\Deployment\DeploymentRepositoryInterface:
        factory:   ['@App\Lti\Builder\DeploymentRepositoryBuilder', 'build']
        arguments: ['%kernel.project_dir%/config/lti.yaml']

    Lcobucci\JWT\Parsing\Encoder: ~

    Lcobucci\JWT\Parser: ~

    Symfony\Component\Yaml\Parser: ~


